CREATE TABLE "{tableName}" (
"id" NUMBER(20) NOT NULL PRIMARY KEY,
"job_id" NVARCHAR2(32) NULL ,
"job_type" NVARCHAR2(32) NULL ,
"priority" NUMBER(11) NULL ,
"retry_times" NUMBER(11) NULL ,
"max_retry_times" NUMBER(11) NULL ,
"rely_on_prev_cycle" NUMBER(4) NULL ,
"task_id" NVARCHAR2(64) NULL ,
"real_task_id" NVARCHAR2(64) NULL ,
"gmt_created" NUMBER(20) NULL ,
"gmt_modified" NUMBER(20) NULL ,
"submit_node_group" NVARCHAR2(64) NULL ,
"task_tracker_node_group" NVARCHAR2(64) NULL ,
"ext_params" NCLOB NULL ,
"internal_ext_params" NCLOB NULL ,
"is_running" NUMBER(4) NULL ,
"task_tracker_identity" NVARCHAR2(64) NULL ,
"need_feedback" NUMBER(4) NULL ,
"cron_expression" NVARCHAR2(128) NULL ,
"trigger_time" NUMBER(20) NULL ,
"repeat_count" NUMBER(11) NULL ,
"repeated_count" NUMBER(11) NULL ,
"repeat_interval" NUMBER(20) NULL ,
"last_generate_trigger_time" NUMBER(20) NULL 
)